import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';

const fonts = Noto_Sans_KR({ subsets: ['latin', 'cyrillic'], weight: ['300', '400', '500', '700'] });

export const metadata: Metadata = {
	title: 'Create Next App', //TODO
	description: 'Generated by create next app', //TODO
};

interface RootLayoutProps {
	children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps): JSX.Element {
	const { children } = props;

	return (
		<html lang='ru'>
			<body className={fonts.className}>{children}</body>
		</html>
	);
}
