import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import { Header } from '@/widgets/Header';
import { SideBar } from '@/widgets/SideBar';
import { Footer } from '@/widgets/Footer';
import { SkipLink } from '@/entities/SkipLink';
import { cn } from '@/shared/helpers/classNames';
import { ButtonUp } from '@/shared/ui/ButtonUp';
import cls from './layout.module.css';
import '@/shared/styles/global.css';

const fonts = Noto_Sans_KR({ subsets: ['latin', 'cyrillic'], weight: ['300', '400', '500', '700'] });

export const metadata: Metadata = {
	title: 'OWNTop',
	description: 'Generated by create next app', //TODO
};

interface RootLayoutProps {
	children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps): JSX.Element {
	const { children } = props;

	return (
		<html lang='ru'>
			<body className={cn(fonts.className, {}, [cls.body])}>
				<SkipLink />
				<Header className={cls.header} menu={<SideBar />} />
				<SideBar className={cls.sideBar} />
				<main className={cls.content} tabIndex={0}>
					{children}
				</main>
				<Footer className={cls.footer} />
				<ButtonUp />
			</body>
		</html>
	);
}
