import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getMenu } from '@/entities/MenuData';
import { getPage } from '@/entities/PageData';
import { TopLevelCategory } from '@/shared/constants/levelCategory';

export const metadata: Metadata = {
	title: 'OWNTop | Продукты',
	description: 'Generated by create next app', //TODO
};

export async function generateStaticParams() {
	const menu = await getMenu(TopLevelCategory.Courses);

	return menu.flatMap((category) =>
		category.pages.map((page) => {
			alias: page.alias;
		})
	);
}

interface ProductsPageProps {
	params: {
		alias: string;
	};
}

export default async function ProductsPage(props: ProductsPageProps): Promise<JSX.Element> {
	const { params } = props;
	const page = await getPage(params.alias);

	if (!page) {
		notFound();
	}

	return (
		<div>
			ProductsPage
			<h1>alias = {params.alias}</h1>
			<h2>title = {page.title}</h2>
		</div>
	);
}
